encoding: UTF-8

markdown: kramdown

kramdown:
  entity_output: as_input
  
exclude: ['README.md']


compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  profile: false
  ignore:
    envs: [development]

sass:
    sass_dir: _sass
    style: :compressed
